# Generated by Django 6.0.2 on 2026-02-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_tippgeberclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexxuser',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='flexxuser',
            name='bank_bic',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='flexxuser',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='flexxuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='TippgeberClient',
        ),
    ]
