# Generated by Django 6.0.2 on 2026-02-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_flexxuser_house_number_tippgeberclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexxuser',
            name='house_number',
        ),
        migrations.DeleteModel(
            name='TippgeberClient',
        ),
    ]
