# Generated by Django 6.0.2 on 2026-02-15 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_remove_flexxuser_house_number_delete_tippgeberclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='TippgeberClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tippgeber_link', to=settings.AUTH_USER_MODEL)),
                ('tippgeber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tippgeber_client_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tippgeber_clients',
            },
        ),
    ]
