# Generated by Django 6.0.2 on 2026-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_flexxuser_bank_depo_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexxuser',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
