# Generated by Django 6.0.2 on 2026-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_rename_depo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tippgeberclient',
            name='expected_investment_amount',
            field=models.FloatField(default=0),
        ),
    ]
