# Generated by Django 6.0.2 on 2026-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bond_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_volume', models.DecimalField(decimal_places=2, max_digits=14)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('extra_term_months', models.PositiveSmallIntegerField(default=0)),
                ('contract', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bond_issues',
                'ordering': ['-issue_date', '-id'],
            },
        ),
    ]
