# Generated by Django 6.0.2 on 2026-02-14 10:21

import django.db.models.deletion
import flexx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondissue',
            name='extra_term_months',
        ),
        migrations.CreateModel(
            name='BondIssueAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=flexx.models.bond_issue_attachment_upload_to)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='flexx.bondissue')),
            ],
            options={
                'db_table': 'bond_issue_attachments',
                'ordering': ['id'],
            },
        ),
    ]
