# Generated by Django 6.0.2 on 2026-02-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0002_remove_bondissue_extra_term_months_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bondissueattachment',
            options={},
        ),
        migrations.RemoveField(
            model_name='bondissueattachment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='bondissueattachment',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bondissueattachment',
            name='file',
            field=models.FileField(upload_to='bond_issues/'),
        ),
    ]
