# Generated by Django 6.0.2 on 2026-02-15 18:52

import django.db.models.deletion
import flexx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0003_alter_bondissueattachment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, upload_to=flexx.models.contract_pdf_upload_to)),
                ('signed_received_at', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_client', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='flexx.bondissue')),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-contract_date', '-id'],
            },
        ),
    ]
