# Generated by Django 6.0.2 on 2026-02-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0004_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondissue',
            name='minimal_bonds_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='bonds_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='nominal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='nominal_amount_plus_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
