# Generated by Django 6.0.2 on 2026-02-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0005_bondissue_minimal_bonds_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('from_role', models.CharField(choices=[('FleXXLager', 'Flexxlager'), ('Tippgeber', 'Tippgeber'), ('Client', 'Client')], max_length=20)),
                ('to_role', models.CharField(choices=[('FleXXLager', 'Flexxlager'), ('Tippgeber', 'Tippgeber'), ('Client', 'Client')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('placeholder', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['key'],
            },
        ),
    ]
