# Generated by Django 6.0.2 on 2026-02-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0006_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='from_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
