# Generated by Django 6.0.2 on 2026-02-23 13:44

import flexx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0007_emailtemplate_from_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexxlagerSignature',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('signature', models.ImageField(upload_to=flexx.models.flexxlager_signature_upload_to)),
            ],
            options={
                'verbose_name': 'FleXXLager Signature',
                'verbose_name_plural': 'FleXXLager Signature',
                'db_table': 'flexxlager_signature',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_signed',
            field=models.FileField(blank=True, upload_to=flexx.models.contract_signed_upload_to),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature',
            field=models.ImageField(blank=True, upload_to=flexx.models.contract_signature_upload_to),
        ),
    ]
