# Generated by Django 6.0.2 on 2026-02-23 13:55

import flexx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0008_flexxlagersignature_contract_contract_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='datenschutzeinwilligung',
            field=models.FileField(blank=True, upload_to=flexx.models.contract_datenschutzeinwilligung_upload_to),
        ),
    ]
