# Generated by Django 6.0.2 on 2026-02-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0009_contract_datenschutzeinwilligung'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatenschutzeinwilligungText',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Datenschutzeinwilligung Text',
                'verbose_name_plural': 'Datenschutzeinwilligung Text',
                'db_table': 'datenschutzeinwilligung_text',
            },
        ),
    ]
