# Generated by Django 6.0.2 on 2026-02-23 15:34

import flexx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flexx", "0010_datenschutzeinwilligungtext"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="pdf_file",
            new_name="contract_pdf",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="contract_signed",
            new_name="contract_pdf_signed",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="datenschutzeinwilligung",
            new_name="datenschutzeinwilligung_pdf",
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_pdf_signed",
            field=models.FileField(blank=True, upload_to=flexx.models.contract_pdf_signed_upload_to),
        ),
        migrations.AlterField(
            model_name="contract",
            name="datenschutzeinwilligung_pdf",
            field=models.FileField(blank=True, upload_to=flexx.models.contract_datenschutzeinwilligung_pdf_upload_to),
        ),
        migrations.AddField(
            model_name="contract",
            name="datenschutzeinwilligung_pdf_signed",
            field=models.FileField(blank=True, upload_to=flexx.models.contract_datenschutzeinwilligung_pdf_signed_upload_to),
        ),
    ]
