# Generated by Django 6.0.2 on 2026-02-26 22:38

import flexx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0011_contract_pdf_fields_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_pdf_signed_signed',
            field=models.FileField(blank=True, upload_to=flexx.models.contract_pdf_signed_upload_to),
        ),
    ]
