# Generated by Django 6.0.2 on 2026-02-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0012_contract_contract_pdf_signed_signed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='datenschutzeinwilligung_pdf',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='datenschutzeinwilligung_pdf_signed',
        ),
    ]
