# Generated by Django 6.0.2 on 2026-03-03 22:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0022_emailtemplate_contract_paid_received_variants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bondissue',
            name='documents_sent_other',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bondissue',
            name='isin_wkn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bondissue',
            name='rate_tippgeber',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='BondIssueSystemDocumentSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_issue_system_document_sends', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_document_sends', to='flexx.bondissue')),
            ],
            options={
                'db_table': 'bond_issue_system_document_sends',
                'ordering': ['-sent_at', '-id'],
            },
        ),
    ]
