# Generated by Django 6.0.2 on 2026-03-05 13:17

import django.db.models.deletion
import flexx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0024_active_client_requires_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TippgeberContractText',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tippgeber Contract Text',
                'verbose_name_plural': 'Tippgeber Contract Text',
                'db_table': 'tippgeber_contract_text',
            },
        ),
        migrations.CreateModel(
            name='TippgeberContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_file', models.FileField(blank=True, upload_to=flexx.models.tippgeber_contract_signature_upload_to)),
                ('signed_contract_pdf', models.FileField(blank=True, upload_to=flexx.models.tippgeber_contract_pdf_upload_to)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tippgeber_contracts', to='flexx.bondissue')),
                ('tippgeber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tippgeber_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tippgeber_contracts',
                'ordering': ['-signed_at', '-id'],
            },
        ),
    ]
