# Generated by Django 6.0.2 on 2026-03-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexx', '0026_fill_tippgeber_contract_text_singleton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatenschutzeinwilligungText',
        ),
    ]
